/**
 * SBOM Generator
 * Software Bill of Materials 자동 생성
 * 정부 제출용 공급망 보안 문서
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

// =============================================================================
// 타입 정의
// =============================================================================

export interface SBOMComponent {
  name: string;
  version: string;
  type: 'library' | 'framework' | 'application';
  purl?: string;              // Package URL
  license?: string;
  supplier?: string;
  hash?: {
    algorithm: string;
    value: string;
  };
  vulnerabilities?: Vulnerability[];
}

export interface Vulnerability {
  id: string;                 // CVE-XXXX-XXXXX
  severity: 'critical' | 'high' | 'medium' | 'low' | 'unknown';
  description: string;
  fixed?: string;             // 수정된 버전
}

export interface SBOM {
  bomFormat: 'CycloneDX' | 'SPDX';
  specVersion: string;
  serialNumber: string;
  version: number;
  metadata: {
    timestamp: string;
    tools: {
      vendor: string;
      name: string;
      version: string;
    }[];
    component: {
      name: string;
      version: string;
      type: string;
    };
  };
  components: SBOMComponent[];
}

// =============================================================================
// SBOM 생성기
// =============================================================================

export class SBOMGenerator {
  private projectRoot: string;

  constructor(projectRoot: string = process.cwd()) {
    this.projectRoot = projectRoot;
  }

  /**
   * package.json 기반 SBOM 생성
   */
  async generate(): Promise<SBOM> {
    const packageJson = this.readPackageJson();

    const components = this.extractComponents(packageJson);

    return {
      bomFormat: 'CycloneDX',
      specVersion: '1.4',
      serialNumber: `urn:uuid:${this.generateUUID()}`,
      version: 1,
      metadata: {
        timestamp: new Date().toISOString(),
        tools: [
          {
            vendor: 'Qetta',
            name: 'sbom-generator',
            version: '1.0.0',
          },
        ],
        component: {
          name: (packageJson.name as string) || 'qetta-mvp-v2',
          version: (packageJson.version as string) || '0.1.0',
          type: 'application',
        },
      },
      components,
    };
  }

  /**
   * CycloneDX JSON 형식으로 내보내기
   */
  async exportCycloneDX(): Promise<string> {
    const sbom = await this.generate();
    return JSON.stringify(sbom, null, 2);
  }

  /**
   * SPDX 형식으로 내보내기
   */
  async exportSPDX(): Promise<string> {
    const sbom = await this.generate();

    const spdx = {
      spdxVersion: 'SPDX-2.3',
      dataLicense: 'CC0-1.0',
      SPDXID: 'SPDXRef-DOCUMENT',
      name: sbom.metadata.component.name,
      documentNamespace: `https://qetta.io/spdx/${sbom.serialNumber}`,
      creationInfo: {
        created: sbom.metadata.timestamp,
        creators: ['Tool: qetta-sbom-generator-1.0.0'],
      },
      packages: sbom.components.map((c, i) => ({
        SPDXID: `SPDXRef-Package-${i}`,
        name: c.name,
        versionInfo: c.version,
        downloadLocation: c.purl || 'NOASSERTION',
        licenseConcluded: c.license || 'NOASSERTION',
        supplier: c.supplier || 'NOASSERTION',
      })),
    };

    return JSON.stringify(spdx, null, 2);
  }

  /**
   * 정부 제출용 요약 보고서 생성
   */
  async generateReport(): Promise<string> {
    const sbom = await this.generate();

    const criticalVulns = sbom.components.filter(
      (c) => c.vulnerabilities?.some((v) => v.severity === 'critical')
    );
    const highVulns = sbom.components.filter(
      (c) => c.vulnerabilities?.some((v) => v.severity === 'high')
    );

    return `
# SBOM 보안 보고서

## 개요
- **프로젝트**: ${sbom.metadata.component.name}
- **버전**: ${sbom.metadata.component.version}
- **생성일**: ${new Date(sbom.metadata.timestamp).toLocaleDateString('ko-KR')}
- **형식**: ${sbom.bomFormat} ${sbom.specVersion}

## 컴포넌트 현황
- **총 컴포넌트 수**: ${sbom.components.length}개
- **라이브러리**: ${sbom.components.filter((c) => c.type === 'library').length}개
- **프레임워크**: ${sbom.components.filter((c) => c.type === 'framework').length}개

## 취약점 현황
- **Critical**: ${criticalVulns.length}개
- **High**: ${highVulns.length}개
${criticalVulns.length > 0 ? `\n### Critical 취약점\n${criticalVulns.map((c) => `- ${c.name}: ${c.vulnerabilities?.find((v) => v.severity === 'critical')?.id}`).join('\n')}` : ''}

## 라이선스 현황
${this.groupByLicense(sbom.components)}

## 결론
${criticalVulns.length === 0 && highVulns.length === 0 ? '✅ 심각한 보안 취약점이 발견되지 않았습니다.' : '⚠️ 보안 취약점이 발견되었습니다. 즉시 업데이트가 필요합니다.'}

---
*Generated by Qetta SBOM Generator*
    `.trim();
  }

  // ==========================================================================
  // Private Methods
  // ==========================================================================

  private readPackageJson(): Record<string, unknown> {
    const packagePath = join(this.projectRoot, 'package.json');

    if (!existsSync(packagePath)) {
      return { name: 'unknown', version: '0.0.0', dependencies: {} };
    }

    const content = readFileSync(packagePath, 'utf-8');
    return JSON.parse(content);
  }

  private extractComponents(packageJson: Record<string, unknown>): SBOMComponent[] {
    const components: SBOMComponent[] = [];
    const deps = packageJson.dependencies as Record<string, string> || {};
    const devDeps = packageJson.devDependencies as Record<string, string> || {};

    // Production dependencies
    for (const [name, version] of Object.entries(deps)) {
      components.push({
        name,
        version: this.cleanVersion(version),
        type: this.inferType(name),
        purl: `pkg:npm/${name}@${this.cleanVersion(version)}`,
        license: this.inferLicense(name),
      });
    }

    // Dev dependencies (선택적)
    for (const [name, version] of Object.entries(devDeps)) {
      components.push({
        name,
        version: this.cleanVersion(version),
        type: 'library',
        purl: `pkg:npm/${name}@${this.cleanVersion(version)}`,
        license: this.inferLicense(name),
      });
    }

    return components;
  }

  private cleanVersion(version: string): string {
    return version.replace(/^[\^~]/, '');
  }

  private inferType(name: string): SBOMComponent['type'] {
    const frameworks = ['next', 'react', 'vue', 'angular', 'express'];
    if (frameworks.some((f) => name.includes(f))) {
      return 'framework';
    }
    return 'library';
  }

  private inferLicense(name: string): string {
    // 주요 패키지 라이선스 (실제로는 npm registry에서 조회)
    const knownLicenses: Record<string, string> = {
      'next': 'MIT',
      'react': 'MIT',
      'typescript': 'Apache-2.0',
      '@supabase/supabase-js': 'MIT',
      'tailwindcss': 'MIT',
    };
    return knownLicenses[name] || 'NOASSERTION';
  }

  private groupByLicense(components: SBOMComponent[]): string {
    const licenseMap: Record<string, number> = {};

    for (const c of components) {
      const license = c.license || 'Unknown';
      licenseMap[license] = (licenseMap[license] || 0) + 1;
    }

    return Object.entries(licenseMap)
      .sort((a, b) => b[1] - a[1])
      .map(([license, count]) => `- ${license}: ${count}개`)
      .join('\n');
  }

  private generateUUID(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }
}

// =============================================================================
// Factory
// =============================================================================

let instance: SBOMGenerator | null = null;

export function getSBOMGenerator(): SBOMGenerator {
  if (!instance) {
    instance = new SBOMGenerator();
  }
  return instance;
}
