/**
 * PPTX Builder - 발표자료 생성기
 * Uses pptxgenjs for PowerPoint document generation
 */

import PptxGenJS from 'pptxgenjs';
import * as fs from 'fs';
import * as path from 'path';
import type { BuilderOptions, BuildResult } from './index';

export interface ProposalPptData {
  title: string;
  subtitle?: string;
  date?: string;
  sections: PptSection[];
  contact?: ContactInfo;
}

export interface PptSection {
  title: string;
  bullets?: string[];
  content?: string;
  imagePath?: string;
  chart?: ChartData;
  table?: PptTableData;
}

export interface ContactInfo {
  company: string;
  name: string;
  email: string;
  phone?: string;
}

export interface ChartData {
  type: 'bar' | 'line' | 'pie';
  labels: string[];
  data: number[];
  title?: string;
}

export interface PptTableData {
  headers: string[];
  rows: string[][];
}

// Qetta 브랜드 컬러
const QETTA_PURPLE = '9333EA';
const QETTA_DARK = '1F2937';
// const QETTA_LIGHT = 'F3E8FF'; // Reserved for future use

export class PptxBuilder {
  private pptx: PptxGenJS;
  private options: BuilderOptions;

  constructor(options: BuilderOptions = {}) {
    this.pptx = new PptxGenJS();
    this.options = {
      language: 'ko',
      author: 'Qetta',
      company: 'Qetta Inc.',
      ...options,
    };

    // 기본 설정
    this.pptx.author = this.options.author || 'Qetta';
    this.pptx.company = this.options.company || 'Qetta Inc.';
    this.pptx.subject = 'Generated by Qetta Document Skills Engine';
    this.pptx.layout = 'LAYOUT_16x9';
  }

  /**
   * 제안 발표자료 생성
   */
  createProposal(data: ProposalPptData): this {
    // 표지
    this.addTitleSlide(data.title, data.subtitle, data.date);

    // 목차
    this.addTocSlide(data.sections.map((s) => s.title));

    // 섹션별 슬라이드
    for (const section of data.sections) {
      this.addSectionSlide(section);
    }

    // 마무리
    this.addClosingSlide(data.contact);

    return this;
  }

  /**
   * 표지 슬라이드
   */
  private addTitleSlide(title: string, subtitle?: string, date?: string): void {
    const slide = this.pptx.addSlide();

    // 배경 - 그라데이션 효과
    slide.background = { color: QETTA_PURPLE };

    // 상단 로고 영역 (추후 로고 추가 가능)
    slide.addText('QETTA', {
      x: 0.5,
      y: 0.3,
      w: 2,
      h: 0.5,
      fontSize: 18,
      bold: true,
      color: 'FFFFFF',
    });

    // 메인 제목
    slide.addText(title, {
      x: 0.5,
      y: 2.2,
      w: '90%',
      h: 1.5,
      fontSize: 44,
      bold: true,
      color: 'FFFFFF',
      align: 'center',
    });

    // 부제
    if (subtitle) {
      slide.addText(subtitle, {
        x: 0.5,
        y: 3.7,
        w: '90%',
        h: 0.8,
        fontSize: 22,
        color: 'E0E0E0',
        align: 'center',
      });
    }

    // 날짜
    if (date) {
      slide.addText(date, {
        x: 0.5,
        y: 4.8,
        w: '90%',
        h: 0.5,
        fontSize: 14,
        color: 'CCCCCC',
        align: 'center',
      });
    }

    // 하단 슬로건
    slide.addText('in·ev·it·able — Data Flows. Evidence Follows.', {
      x: 0.5,
      y: 5.0,
      w: '90%',
      h: 0.4,
      fontSize: 12,
      italic: true,
      color: 'AAAAAA',
      align: 'center',
    });
  }

  /**
   * 목차 슬라이드
   */
  private addTocSlide(items: string[]): void {
    const slide = this.pptx.addSlide();

    slide.addText('목 차', {
      x: 0.5,
      y: 0.4,
      w: '90%',
      h: 0.8,
      fontSize: 32,
      bold: true,
      color: QETTA_PURPLE,
    });

    // 구분선
    slide.addShape('rect', {
      x: 0.5,
      y: 1.1,
      w: 2,
      h: 0.05,
      fill: { color: QETTA_PURPLE },
    });

    // 목차 항목
    const tocItems = items.map((item, i) => ({
      text: `${String(i + 1).padStart(2, '0')}  ${item}`,
      options: {
        fontSize: 18,
        color: QETTA_DARK,
        bullet: false,
        paraSpaceAfter: 12,
      },
    }));

    slide.addText(tocItems, {
      x: 0.8,
      y: 1.5,
      w: '85%',
      h: 4,
      valign: 'top',
    });
  }

  /**
   * 섹션 슬라이드
   */
  private addSectionSlide(section: PptSection): void {
    const slide = this.pptx.addSlide();

    // 상단 바
    slide.addShape('rect', {
      x: 0,
      y: 0,
      w: '100%',
      h: 0.08,
      fill: { color: QETTA_PURPLE },
    });

    // 제목
    slide.addText(section.title, {
      x: 0.5,
      y: 0.3,
      w: '90%',
      h: 0.7,
      fontSize: 28,
      bold: true,
      color: QETTA_PURPLE,
    });

    // 구분선
    slide.addShape('rect', {
      x: 0.5,
      y: 0.95,
      w: 1.5,
      h: 0.03,
      fill: { color: QETTA_PURPLE },
    });

    let contentY = 1.3;

    // 본문 텍스트
    if (section.content) {
      slide.addText(section.content, {
        x: 0.5,
        y: contentY,
        w: section.imagePath ? '55%' : '90%',
        h: 3.5,
        fontSize: 16,
        color: QETTA_DARK,
        valign: 'top',
      });
      contentY += 1;
    }

    // 불릿 리스트
    if (section.bullets && section.bullets.length > 0) {
      const bulletItems = section.bullets.map((b) => ({
        text: b,
        options: {
          fontSize: 16,
          color: QETTA_DARK,
          bullet: { type: 'bullet' as const, color: QETTA_PURPLE },
          paraSpaceAfter: 8,
        },
      }));

      slide.addText(bulletItems, {
        x: 0.5,
        y: contentY,
        w: section.imagePath ? '55%' : '90%',
        h: 3.5,
        valign: 'top',
      });
    }

    // 이미지
    if (section.imagePath && fs.existsSync(section.imagePath)) {
      slide.addImage({
        path: section.imagePath,
        x: 6.5,
        y: 1.3,
        w: 3.3,
        h: 3.3,
      });
    }

    // 차트
    if (section.chart) {
      this.addChart(slide, section.chart);
    }

    // 테이블
    if (section.table) {
      this.addTable(slide, section.table);
    }

    // 페이지 번호
    slide.addText('QETTA', {
      x: 0.3,
      y: 5.1,
      w: 1,
      h: 0.3,
      fontSize: 10,
      color: 'AAAAAA',
    });
  }

  /**
   * 차트 추가
   */
  private addChart(slide: PptxGenJS.Slide, chartData: ChartData): void {
    const chartType = chartData.type === 'pie' ? 'pie' : chartData.type === 'line' ? 'line' : 'bar';

    slide.addChart(chartType, [
      {
        name: chartData.title || 'Data',
        labels: chartData.labels,
        values: chartData.data,
      },
    ], {
      x: 0.5,
      y: 2,
      w: 5,
      h: 3,
      chartColors: [QETTA_PURPLE, '60A5FA', '34D399', 'FBBF24', 'F87171'],
      showTitle: !!chartData.title,
      title: chartData.title,
    });
  }

  /**
   * 테이블 추가
   */
  private addTable(slide: PptxGenJS.Slide, tableData: PptTableData): void {
    const rows: PptxGenJS.TableRow[] = [
      // Header
      tableData.headers.map((h) => ({
        text: h,
        options: {
          bold: true,
          fill: { color: QETTA_PURPLE },
          color: 'FFFFFF',
          align: 'center' as const,
        },
      })),
      // Data
      ...tableData.rows.map((row) =>
        row.map((cell) => ({
          text: cell,
          options: {
            align: 'center' as const,
          },
        }))
      ),
    ];

    slide.addTable(rows, {
      x: 0.5,
      y: 2,
      w: 9,
      colW: Array(tableData.headers.length).fill(9 / tableData.headers.length),
      border: { type: 'solid', pt: 1, color: 'CCCCCC' },
      fontFace: 'Arial',
      fontSize: 12,
    });
  }

  /**
   * 마무리 슬라이드
   */
  private addClosingSlide(contact?: ContactInfo): void {
    const slide = this.pptx.addSlide();

    slide.background = { color: QETTA_PURPLE };

    // 감사 메시지
    slide.addText('감사합니다', {
      x: 0.5,
      y: 1.8,
      w: '90%',
      h: 1.5,
      fontSize: 48,
      bold: true,
      color: 'FFFFFF',
      align: 'center',
    });

    // 슬로건
    slide.addText('in·ev·it·able — Data Flows. Evidence Follows.', {
      x: 0.5,
      y: 3.2,
      w: '90%',
      h: 0.5,
      fontSize: 16,
      italic: true,
      color: 'E0E0E0',
      align: 'center',
    });

    // 연락처
    if (contact) {
      slide.addText(
        [
          { text: contact.company, options: { fontSize: 18, bold: true } },
          { text: '\n', options: { fontSize: 10 } },
          {
            text: `${contact.name} | ${contact.email}${contact.phone ? ' | ' + contact.phone : ''}`,
            options: { fontSize: 14 },
          },
        ],
        {
          x: 0.5,
          y: 4.2,
          w: '90%',
          h: 1,
          color: 'E0E0E0',
          align: 'center',
        }
      );
    }
  }

  /**
   * 파일 저장
   */
  async save(outputPath: string): Promise<BuildResult> {
    try {
      const dir = path.dirname(outputPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // pptxgenjs는 확장자 자동 처리
      const fileName = outputPath.endsWith('.pptx') ? outputPath : `${outputPath}.pptx`;

      await this.pptx.writeFile({ fileName });

      if (fs.existsSync(fileName)) {
        const stats = fs.statSync(fileName);
        return {
          success: true,
          filePath: fileName,
          fileSize: stats.size,
        };
      }

      return { success: false, error: 'File not created' };
    } catch (error) {
      return {
        success: false,
        error: String(error),
      };
    }
  }

  /**
   * Buffer 반환
   */
  async toBuffer(): Promise<Buffer> {
    const data = await this.pptx.write({ outputType: 'nodebuffer' });
    return data as Buffer;
  }
}
